//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.BL_Article = new HashSet<BL_Article>();
            this.Photos = new HashSet<Photo>();
            this.References = new HashSet<Reference>();
        }
    
        public int art_Code { get; set; }
        public string art_Designatiion { get; set; }
        public string art_Description { get; set; }
        public Nullable<int> svc_Code { get; set; }
        public Nullable<int> fam_Code { get; set; }
        public Nullable<int> msr_Code { get; set; }
    
        public virtual Famille Famille { get; set; }
        public virtual Service Service { get; set; }
        public virtual Unite_Mesure Unite_Mesure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BL_Article> BL_Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reference> References { get; set; }
    }
}
