//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon_Livraison
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bon_Livraison()
        {
            this.BL_Article = new HashSet<BL_Article>();
        }
    
        public int bl_Code { get; set; }
        public Nullable<System.DateTime> bl_Date { get; set; }
        public string bl_Reference { get; set; }
        public Nullable<int> frns_Code { get; set; }
        public Nullable<int> unit_Code { get; set; }
        public Nullable<int> typ_Code { get; set; }
        public string bl_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BL_Article> BL_Article { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
        public virtual Operation_Type Operation_Type { get; set; }
        public virtual Unite Unite { get; set; }
    }
}
