//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gesStock_FAEntities : DbContext
    {
        public gesStock_FAEntities()
            : base("name=gesStock_FAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<BL_Article> BL_Article { get; set; }
        public virtual DbSet<Bon_Livraison> Bon_Livraison { get; set; }
        public virtual DbSet<CodeBarre> CodeBarres { get; set; }
        public virtual DbSet<Emplacement> Emplacements { get; set; }
        public virtual DbSet<Etager> Etagers { get; set; }
        public virtual DbSet<Famille> Familles { get; set; }
        public virtual DbSet<Fournisseur> Fournisseurs { get; set; }
        public virtual DbSet<Magasin> Magasins { get; set; }
        public virtual DbSet<Mvt_Stock> Mvt_Stock { get; set; }
        public virtual DbSet<Operation_Type> Operation_Type { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Rayonnage> Rayonnages { get; set; }
        public virtual DbSet<Reference> References { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Unite> Unites { get; set; }
        public virtual DbSet<Unite_Mesure> Unite_Mesure { get; set; }
        public virtual DbSet<Vehicule> Vehicules { get; set; }
    }
}
