//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mvt_Stock
    {
        public int mvt_Code { get; set; }
        public Nullable<System.DateTime> mvt_Date { get; set; }
        public string mvt_Doc_Refference { get; set; }
        public Nullable<int> frns_Code { get; set; }
        public Nullable<int> unit_Code { get; set; }
        public Nullable<int> typ_Code { get; set; }
        public Nullable<decimal> mvt_Qte_Demandee { get; set; }
        public Nullable<decimal> mvt_Qte_Livree { get; set; }
        public Nullable<int> msr_Code { get; set; }
        public Nullable<int> bl_A_Code { get; set; }
        public string mvt_Obsrvation { get; set; }
    
        public virtual BL_Article BL_Article { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
        public virtual Operation_Type Operation_Type { get; set; }
        public virtual Unite Unite { get; set; }
        public virtual Unite_Mesure Unite_Mesure { get; set; }
    }
}
